# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{simply_stored}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mathias Meyer, Jonathan Weiss"]
  s.date = %q{2009-10-16}
  s.description = %q{Convenience layer for CouchDB and SimpleDB. Requires CouchPotato and RightAWS library respectively.}
  s.email = %q{info@peritor.com}
  s.files = [
    "lib/simply_stored.rb",
     "lib/simply_stored/class_methods_base.rb",
     "lib/simply_stored/couch.rb",
     "lib/simply_stored/couch/belongs_to.rb",
     "lib/simply_stored/couch/ext/couch_potato.rb",
     "lib/simply_stored/couch/has_many.rb",
     "lib/simply_stored/couch/has_one.rb",
     "lib/simply_stored/couch/validations.rb",
     "lib/simply_stored/couch/views.rb",
     "lib/simply_stored/couch/views/array_property_view_spec.rb",
     "lib/simply_stored/instance_methods.rb",
     "lib/simply_stored/storage.rb"
  ]
  s.homepage = %q{http://github.com/peritor/simply_stored}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.4}
  s.summary = %q{Convenience layer for CouchDB and SimpleDB}
  s.test_files = [
    "test/custom_views_test.rb",
     "test/fixtures/couch.rb",
     "test/simply_stored_couch_test.rb",
     "test/test_helper.rb"
  ]
  
  s.add_dependency "couch_potato", ">=0.2.14"

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
